# Generated by Django 2.2.15 on 2020-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaTurtleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('shell_size', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'permissions': (('can_eat_pizza', 'Can Eat Pizza'),),
            },
        ),
        migrations.CreateModel(
            name='SenseiRatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
