# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodumpdata.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autodumpdata.Publication')),
                ('is_hardcover', models.BooleanField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('autodumpdata.publication',),
        ),
        migrations.CreateModel(
            name='PublicationProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('autodumpdata.publication',),
        ),
        migrations.AddField(
            model_name='authorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodumpdata.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='authored',
            field=models.ManyToManyField(related_name='authors', through='autodumpdata.AuthorBook', to='autodumpdata.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='edited',
            field=models.ManyToManyField(related_name='editors', to='autodumpdata.Book'),
        ),
        migrations.CreateModel(
            name='BookProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('autodumpdata.book',),
        ),
    ]
