# Generated by Django 2.2.15 on 2021-07-18 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import test_allianceutils.tests.profile_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', test_allianceutils.tests.profile_auth.models.UserManager()),
                ('profiles', test_allianceutils.tests.profile_auth.models.UserManager(select_related_profiles=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFKImmediateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_details', models.CharField(max_length=191)),
            ],
            bases=('profile_auth.user',),
            managers=[
                ('objects', test_allianceutils.tests.profile_auth.models.UserManager()),
                ('profiles', test_allianceutils.tests.profile_auth.models.UserManager(select_related_profiles=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_details', models.CharField(max_length=191)),
            ],
            bases=('profile_auth.user',),
            managers=[
                ('objects', test_allianceutils.tests.profile_auth.models.UserManager()),
                ('profiles', test_allianceutils.tests.profile_auth.models.UserManager(select_related_profiles=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFKIndirectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_auth.UserFKImmediateModel')),
            ],
        ),
    ]
