# Generated by Django 2.2 on 2019-10-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_auth', '0002_auto_20190929_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
