# syntax can be found at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Django CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # the combinations can run in parallel by adjusting this value
      max-parallel: 20
      # all combinations of the matrix choices below are combined to create jobs. The max combinations is 256
      # Note that the TOX_ENV_RE regex is then used to filter these combinations
      # to those that are listed in tox.ini
      matrix:
        python-version: ['38', '39', '310', '311']
        database-type: ['postgresql', 'mysql']

    services:

      postgresql:
        # Docker Hub image
        image: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        env:
          # Override Django DB settings
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Downloads a copy of the code in the repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup the next version of python in the versions matrix
      - name: Set up Python 3.8
        if: ${{ matrix.python-version == '38' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Python 3.9
        if: ${{ matrix.python-version == '39' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Python 3.10
        if: ${{ matrix.python-version == '310' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Set up Python 3.11
        if: ${{ matrix.python-version == '311' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-factor

      # postgres tests
      - name: Run PostgreSQL Tests with   py${{ matrix.python-version }}
        if: ${{ matrix.database-type == 'postgresql' }}
        run: bin/runtests.sh
        env:
          CI_SERVER: yes
          TOX_ENV_RE: py${{ matrix.python-version }}-.*${{ matrix.database-type }}
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgresql.ports[5432] }}
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres

      # mysql tests
      - name: Start MySQL service
        if: ${{ matrix.database-type == 'mysql' }}
        run: sudo /etc/init.d/mysql start

      - name: Run MySQL Tests with py${{ matrix.python-version }}
        if: ${{ matrix.database-type == 'mysql' }}
        run: bin/runtests.sh
        env:
          CI_SERVER: yes
          TOX_ENV_RE: py${{ matrix.python-version }}-.*${{ matrix.database-type }}
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
          DB_PASSWORD: password
